### ISSUE TITLE
Delay() inside the library 

### ISSUE THREAD

**Issue by ndanilo8** [sparkfun/SparkFun_PHT_MS8607_Arduino_Library#3]
Hey!
I've been using this library for a real time system but during testing I found out something was "delaying" my code and after some digging I noticed this library uses the delay() function... would you be kind to fix this issue? or is there a way someone could give me a hand to remove this delay() functions?
I tried adding a If statement timer where I found the delay functions.. but they don't work. 

The lines where there are delays: 
https://github.com/sparkfun/SparkFun_PHT_MS8607_Arduino_Library/blob/master/src/SparkFun_PHT_MS8607_Arduino_Library.cpp#L252

https://github.com/sparkfun/SparkFun_PHT_MS8607_Arduino_Library/blob/master/src/SparkFun_PHT_MS8607_Arduino_Library.cpp#L455

https://github.com/sparkfun/SparkFun_PHT_MS8607_Arduino_Library/blob/master/src/SparkFun_PHT_MS8607_Arduino_Library.cpp#L764

Appreciate your input

**Comment by PaulZC** [comment]
Hi Danilo (@ndanilo8 ),
If you look at line 764 for example, the code requests a pressure reading, waits the required 20ms for the conversion to complete, then reads and returns the sensor value.
If you want to remove the delay, you will need to re-structure the code, breaking functions like that up into two functions: one to request the reading; and a second to read the reading.
That is not something we can do for you.
Best wishes,
Paul

**Comment by ndanilo8** [comment]
Hey @PaulZC Thanks for your time.
I've tried to do what you said: separate the request and read functions. But I'm still not able to get data out of the sensor. 
When I read the Pressure I get back a NaN and the Temperature a negative number.
I really hope I can make this work. Otherwise I will have to buy another sensor like a BMP or a BME and that is last resort.

So if you don't mind, please help me debug what I'm doing wrong.
I attached the modded library (.zip)

**The changes:**

- 2 new functions:` request_data` &` read_adc `(line 566 of the header)
- ^ this two function can be found on (798 line of the source )
- edited `psensor_read_pressure_and_temperature` function (line 859 of the source)


[SparkFun_PHT_MS8607_Arduino_Library.zip](https://github.com/sparkfun/SparkFun_PHT_MS8607_Arduino_Library/files/6528045/SparkFun_PHT_MS8607_Arduino_Library.zip)

I appreciate your input

**Comment by PaulZC** [comment]
Hi Danilo,
Sorry - I don't have the time to debug this for you....
You could try asking for help in the Qwiic forum: https://forum.sparkfun.com/viewforum.php?f=105
Best wishes,
Paul
