### ISSUE TITLE
Push latest version to Particle library

### ISSUE THREAD

**Issue by metcalf** [sparkfun/SparkFun_PHT_MS8607_Arduino_Library#4]
I'd like to use this for a Particle project but it appears that Particle is a few versions behind. Could you please push the latest version of this library? 

Reference: https://docs.particle.io/cards/libraries/s/SparkFun_PHT_MS8607_Arduino_Library/

**Comment by PaulZC** [comment]
Hi Andrew (@metcalf ),

To the best of my knowledge, we don't submit our libraries to Particle directly. It looks like Particle has been picking them up automatically? I suspect you will need to ask Particle to pull the latest version.

Best wishes,
Paul
